import { z } from "zod";

export const CreateAuctionSchema = z.object({
  title: z.string().min(3, "Title must be at least 3 characters"),
  description: z.string().min(10, "Description must be at least 10 characters"),
  startingPrice: z.number().min(1, "Starting price must be at least 1"),
  category: z.enum([
    "Art",
    "Electronics",
    "Vehicles",
    "Collectibles",
    "Fashion",
    "Real Estate",
    "Textiles",
    "Jewelry",
    "Antiques",
    "Food & Spices",
    "Handicrafts",
    "Musical Instruments",
    "Books & Manuscripts",
    "Furniture",
    "Sports & Gear",
    "Home & Living",
    "Industrial Equipment",
    "Luxury Goods",
    "Agriculture & Livestock",
    "Tools & Hardware",
    "Ceramics & Pottery",
    "Carpets & Rugs",
    "Coins & Currency",
    "Watches & Timepieces",
    "Photography",
    "Sculptures",
    "Paintings",
    "Textbooks & Academic",
    "Outdoor & Adventure",
    "Health & Wellness",
    "Office Supplies",
    "Children & Toys",
    "Cultural Heritage",
    "Religious Items",
    "Digital Assets",
  ]),
  endsAt: z.string().optional(),
  imageUrls: z.array(z.string()).optional(),
});

export type CreateAuctionDTO = z.infer<typeof CreateAuctionSchema>;
